# This workflow will create a release when a `v*` tag is pushed
# For more information see: https://github.com/actions/create-release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    # Map step output to job output
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url  }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true

  benchmarks:
    name: Run benchmarks
    runs-on: [self-hosted, linux, x64]
    needs: [build]
    strategy:
      matrix:
        jdk: [11, 16]
        implementation: ["f2j", "java"]
        include:
        - jdk: 16
          implementation: "vector"
          jvmArgs: "--add-modules=jdk.incubator.vector"
        - jdk: 16
          implementation: "native"
          jvmArgs: "--add-modules=jdk.incubator.foreign -Dforeign.restricted=permit"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build
      run: mvn --batch-mode -Dmaven.test.skip=true -Dmaven.javadoc.skip=true package

    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Run benchmark
      run: java -jar benchmarks/target/netlib-benchmarks.jar -p implementation=${{ matrix.implementation }} -jvmArgs "${{ matrix.jvmArgs }}" -rf json -rff jmh-results-jdk${{ matrix.jdk }}-${{ matrix.implementation }}.json | tee jmh-jdk${{ matrix.jdk }}-${{ matrix.implementation }}.out
    - name: Upload JMH results
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build.outputs.release_upload_url }}
        asset_path: jmh-results-jdk${{ matrix.jdk }}-${{ matrix.implementation }}.json
        asset_name: jmh-results-jdk${{ matrix.jdk }}-${{ matrix.implementation }}.json
        asset_content_type: application/json
    - name: Upload JMH output
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build.outputs.release_upload_url }}
        asset_path: jmh-jdk${{ matrix.jdk }}-${{ matrix.implementation }}.out
        asset_name: jmh-jdk${{ matrix.jdk }}-${{ matrix.implementation }}.out
        asset_content_type: text/plain
